{% set version = "1.2" %}

package:
  name: py3c
  version: {{ version }}

source:
  url: https://github.com/encukou/py3c/archive/v{{ version }}.tar.gz
  sha256: 0e28ea43f5f092967a344294194f55a81fb55adc3c17a0314545d606eb5f6267

build:
  number: 0

requirements:
  build:
    - posix  # [win]
  host:

test:
  commands:
    - test -f "${PREFIX}/include/py3c.h"           # [unix]
    - test -d "${PREFIX}/include/py3c"             # [unix]
    - if not exist "%LIBRARY_INC%\\py3c.h" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\py3c" exit 1    # [win]

about:
  home: https://github.com/encukou/py3c
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: A Python 2/3 compatibility layer for C extensions

  dev_url: https://github.com/encukou/py3c
  doc_url: https://py3c.readthedocs.org/

extra:
  recipe-maintainers:
    - jakirkham
