travis:
  secure:
    BINSTAR_TOKEN: AAybY4OK+C7xXFJrjHIOHBom06Dv2vZghSAH1kDNyFCx3f0gH4UPrL57oyKJqtJ6BoH+XjlEaR347kPWZizCvlBLUbibOACzMgFS5bKfQijRIZtNdwzaUnoOum8kjDRnky0MECXYz9oewlyEXOG9QxM5k9MB74bOst0SaD+qQ3wylZ/9rT92r0f07GoIKJZFUPR5KRHCx3IMP3b4MlDwDbI8xI/8kThS2rpEAK2dvFFkpfvD2rsfnq4iNvTSodobNqeHKd3zq58QEV/ZjlK7Td3QdcrCUkgQ/ST/D/f0iAoitKLyegCKP0iJGQAHBbq6ukJFDrgXnX20TkcFBL5phJJFaGKWKqsUjdFrbrMZutlKh65R+kflXY1jpcAgTj6vSdLEdEIKtGQffInkMIxc2TSN+XLCIsQVPZTwyBs0M1j1+DAsHntHD3ixRapw2E733s+Cs8WvhjwheZ7pKnQBub3Y8e/g50ICF0FpulopsgBl3aJQYmPfhz999tVCH2pYZ5rail7gvaOmUE05qqvgsTsPw4Ym7QimlEbNr3M4EreyVQWKaI7aQqAAY00/LLT00moOO9Q0C39GcNEvSFm91+hnZ7mXBos2hDohgC8ihwo5OrVLbE0/uvyzomePrdkW7pa+MMaRBnWWc0w+xSmMN4xZKqEsa62ODwBiEFKi5go=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
